## Basic info

Read the data-file (a 10 000 row subset of most rated IMDB-movies) into Pandas DataFrame and name the DataFrame-variable to `df` (use tab-character (`\t`) as the separator)

1. Use the following column-names: `ID, title, year, rating, votes, duration, genres`
2. Index the `df` with `ID`-column (either on reading the file or after it.)
3. Display first 5 rows of the `df`
4. Display last 11 rows of the `df`
5. Display the `df`-info

In [1]:
import pandas as pd

In [23]:
df = pd.read_csv("movie_data .txt",delimiter="\t", header=None)
print(df.head())

           0                                1     2    3       4          5  \
0  tt0111161  The Shawshank Redemption (1994)  1994  9.2  619479  142 mins.
1  tt0110912              Pulp Fiction (1994)  1994  9.0  490065  154 mins.
2  tt0137523                Fight Club (1999)  1999  8.8  458173  139 mins.
3  tt0133093                The Matrix (1999)  1999  8.7  448114  136 mins.
4  tt1375666                 Inception (2010)  2010  8.9  385149  148 mins.

                                  6
0                       Crime|Drama
1                    Crime|Thriller
2            Drama|Mystery|Thriller
3           Action|Adventure|Sci-Fi
4  Action|Adventure|Sci-Fi|Thriller

In [24]:
# Index the `df` with `ID`-column (either on reading the file or after it.)
df_columns = ['ID', 'title', 'year', 'rating', 'votes', 'duration', 'genres']
df.columns = df_columns
df

,ID,title,year,rating,votes,duration,genres
0,tt0111161,The Shawshank Redemption (1994),1994,9.2,619479,142 mins.,Crime|Drama
1,tt0110912,Pulp Fiction (1994),1994,9.0,490065,154 mins.,Crime|Thriller
2,tt0137523,Fight Club (1999),1999,8.8,458173,139 mins.,Drama|Mystery|Thriller
3,tt0133093,The Matrix (1999),1999,8.7,448114,136 mins.,Action|Adventure|Sci-Fi
4,tt1375666,Inception (2010),2010,8.9,385149,148 mins.,Action|Adventure|Sci-Fi|Thriller
5,tt0109830,Forrest Gump (1994),1994,8.7,368994,142 mins.,Comedy|Drama|Romance
6,tt0169547,American Beauty (1999),1999,8.6,338332,122 mins.,Drama
7,tt0499549,Avatar (2009),2009,8.1,336855,162 mins.,Action|Adventure|Fantasy|Sci-Fi
8,tt0108052,Schindler's List (1993),1993,8.9,325888,195 mins.,Biography|Drama|History|War
9,tt0080684,Star Wars: Episode V - The Empire Strikes Back...,1980,8.8,320105,124 mins.,Action|Adventure|Family|Sci-Fi
10,tt0372784,Batman Begins (2005),2005,8.3,316613,140 mins.,Action|Crime|Drama|Thriller
11,tt0114814,The Usual Suspects (1995),1995,8.7,306624,106 mins.,Crime|Mystery|Thriller
12,tt0102926,The Silence of the Lambs (1991),1991,8.7,293081,118 mins.,Crime|Thriller
13,tt0120338,Titanic (1997),1997,7.4,284245,194 mins.,Adventure|Drama|History|Romance
14,tt0112573,Braveheart (1995),1995,8.4,281446,177 mins.,Action|Biography|Drama|History|War
15,tt0167404,The Sixth Sense (1999),1999,8.2,278210,107 mins.,Drama|Mystery|Thriller
16,tt0266697,Kill Bill: Vol. 1 (2003),2003,8.2,272983,111 mins.,Action|Crime|Thriller
17,tt0099685,Goodfellas (1990),1990,8.8,270728,146 mins.,Biography|Crime|Drama|Thriller
18,tt0416449,300 (2006),2006,7.8,269328,117 mins.,Action|Fantasy|History|War
19,tt0482571,The Prestige (2006),2006,8.4,258396,130 mins.,Drama|Mystery|Thriller
20,tt0105236,Reservoir Dogs (1992),1992,8.4,247390,99 mins.,Crime|Mystery|Thriller
21,tt0110413,Leon: The Professional (1994),1994,8.6,244568,110 mins.,Crime|Drama|Thriller
22,tt0120689,The Green Mile (1999),1999,8.4,243660,189 mins.,Crime|Drama|Fantasy|Mystery
23,tt0361748,Inglourious Basterds (2009),2009,8.4,240995,153 mins.,Adventure|Drama|War
24,tt0910970,WALL\xb7E (2008),2008,8.5,229364,98 mins.,Animation|Adventure|Family|Romance|Sci-Fi
25,tt0468569,The Dark Knight (2008),2008,8.9,555122,152 mins.,Action|Crime|Drama|Thriller
26,tt0068646,The Godfather (1972),1972,9.2,474189,175 mins.,Crime|Drama
27,tt0120737,The Lord of the Rings: The Fellowship of the R...,2001,8.8,451263,178 mins.,Action|Adventure|Drama|Fantasy
28,tt0167260,The Lord of the Rings: The Return of the King ...,2003,8.8,428791,201 mins.,Action|Adventure|Drama|Fantasy
29,tt0167261,The Lord of the Rings: The Two Towers (2002),2002,8.7,383113,179 mins.,Action|Adventure|Drama|Fantasy
...,...,...,...,...,...,...,...
9970,tt0469897,Diggers (2006),2006,6.4,1358,96 mins.,Comedy|Drama
9971,tt0110064,House Party 3 (1994),1994,3.1,1357,100 mins.,Comedy|Music|Romance
9972,tt1629391,Tere Bin Laden (2010),2010,7.2,1357,95 mins.,Comedy|Drama
9973,tt0878674,Garage (2007),2007,6.9,1356,00 mins.,Drama
9974,tt0076391,Mimino (1977),1977,8.2,1356,97 mins.,Comedy
9975,tt1316037,Birdemic: Shock and Terror (2008),2008,2.0,1366,90 mins.,Horror|Romance|Thriller
9976,tt0197094,What Becomes of the Broken Hearted? (1999),1999,6.3,1365,00 mins.,Drama
9977,tt0092608,Back to the Beach (1987),1987,5.1,1364,92 mins.,Comedy
9978,tt0093175,Hello Again (1987),1987,4.5,1364,96 mins.,Comedy|Drama|Fantasy|Romance
9979,tt1034320,Major Movie Star (2008),2008,3.8,1364,98 mins.,Adventure|Comedy|Drama|War
9980,tt0066476,The Touch of Satan (1971),1971,2.0,1364,90 mins.,Horror
9981,tt1281374,Don McKay (2009),2009,6.0,1363,87 mins.,Drama|Thriller|Mystery
9982,tt0263124,Brainstorm (2001),2001,7.8,1362,74 mins.,Drama
9983,tt0368259,Sex Lives of the Potato Men (2004),2004,4.3,1362,82 mins.,Comedy
9984,tt0067333,Lawman (1971),1971,6.8,1362,99 mins.,Western
9985,tt0065669,The Dunwich Horror (1970),1970,5.1,1361,90 mins.,Horror
9986,tt0048198,I Live in Fear (1955),1955,7.3,1360,103 mins.,Drama
9987,tt0100046,The Long Walk Home (1990),1990,7.2,1360,97 mins.,Drama|History
9988,tt0116247,Evil Ed (1995),1995,5.0,1359,93 mins.,Horror|Comedy
9989,tt0101356,Another You (1991),1991,4.9,1359,98 mins.,Comedy|Crime
9990,tt0421090,Zerophilia (2005),2005,6.3,1359,90 mins.,Comedy|Romance
9991,tt0067227,The Merchant of Four Seasons (1971),1971,7.6,1359,88 mins.,Drama
9992,tt0339727,Stateside (2004),2004,5.8,1358,97 mins.,Drama|Music|Romance
9993,tt0218581,Scarlet Diva (2000),2000,5.2,1358,91 mins.,Drama
9994,tt0118635,Aprile (1998),1998,6.7,1358,78 mins.,Comedy
9995,tt0807721,Meduzot (2007),2007,7.0,1357,78 mins.,Drama
9996,tt0339642,Daltry Calhoun (2005),2005,5.2,1357,100 mins.,Comedy|Drama|Music|Romance
9997,tt0060880,The Quiller Memorandum (1966),1966,6.5,1356,104 mins.,Drama|Mystery|Thriller
9998,tt0152836,Taal (1999),1999,6.5,1356,179 mins.,Musical|Romance
9999,tt0279977,The Navigators (2001),2001,6.9,1356,96 mins.,Comedy|Drama

In [4]:
# Display first 5 rows of the `df`
df.head(5)

,ID,title,year,rating,votes,duration,genres
0,tt0111161,The Shawshank Redemption (1994),1994,9.2,619479,142 mins.,Crime|Drama
1,tt0110912,Pulp Fiction (1994),1994,9.0,490065,154 mins.,Crime|Thriller
2,tt0137523,Fight Club (1999),1999,8.8,458173,139 mins.,Drama|Mystery|Thriller
3,tt0133093,The Matrix (1999),1999,8.7,448114,136 mins.,Action|Adventure|Sci-Fi
4,tt1375666,Inception (2010),2010,8.9,385149,148 mins.,Action|Adventure|Sci-Fi|Thriller

In [25]:
#Display last 11 rows of the `df`
df.tail(11)

,ID,title,year,rating,votes,duration,genres
9989,tt0101356,Another You (1991),1991,4.9,1359,98 mins.,Comedy|Crime
9990,tt0421090,Zerophilia (2005),2005,6.3,1359,90 mins.,Comedy|Romance
9991,tt0067227,The Merchant of Four Seasons (1971),1971,7.6,1359,88 mins.,Drama
9992,tt0339727,Stateside (2004),2004,5.8,1358,97 mins.,Drama|Music|Romance
9993,tt0218581,Scarlet Diva (2000),2000,5.2,1358,91 mins.,Drama
9994,tt0118635,Aprile (1998),1998,6.7,1358,78 mins.,Comedy
9995,tt0807721,Meduzot (2007),2007,7.0,1357,78 mins.,Drama
9996,tt0339642,Daltry Calhoun (2005),2005,5.2,1357,100 mins.,Comedy|Drama|Music|Romance
9997,tt0060880,The Quiller Memorandum (1966),1966,6.5,1356,104 mins.,Drama|Mystery|Thriller
9998,tt0152836,Taal (1999),1999,6.5,1356,179 mins.,Musical|Romance
9999,tt0279977,The Navigators (2001),2001,6.9,1356,96 mins.,Comedy|Drama

In [26]:
#Display the `df`-info
df.info

<bound method DataFrame.info of              ID                                              title  year  \
0     tt0111161                    The Shawshank Redemption (1994)  1994
1     tt0110912                                Pulp Fiction (1994)  1994
2     tt0137523                                  Fight Club (1999)  1999
3     tt0133093                                  The Matrix (1999)  1999
4     tt1375666                                   Inception (2010)  2010
5     tt0109830                                Forrest Gump (1994)  1994
6     tt0169547                             American Beauty (1999)  1999
7     tt0499549                                      Avatar (2009)  2009
8     tt0108052                            Schindler's List (1993)  1993
9     tt0080684  Star Wars: Episode V - The Empire Strikes Back...  1980
10    tt0372784                               Batman Begins (2005)  2005
11    tt0114814                          The Usual Suspects (1995)  1995
12    tt0102926                    The Silence of the Lambs (1991)  1991
13    tt0120338                                     Titanic (1997)  1997
14    tt0112573                                  Braveheart (1995)  1995
15    tt0167404                             The Sixth Sense (1999)  1999
16    tt0266697                           Kill Bill: Vol. 1 (2003)  2003
17    tt0099685                                  Goodfellas (1990)  1990
18    tt0416449                                         300 (2006)  2006
19    tt0482571                                The Prestige (2006)  2006
20    tt0105236                              Reservoir Dogs (1992)  1992
21    tt0110413                      Leon: The Professional (1994)  1994
22    tt0120689                              The Green Mile (1999)  1999
23    tt0361748                        Inglourious Basterds (2009)  2009
24    tt0910970                                   WALL\xb7E (2008)  2008
25    tt0468569                             The Dark Knight (2008)  2008
26    tt0068646                               The Godfather (1972)  1972
27    tt0120737  The Lord of the Rings: The Fellowship of the R...  2001
28    tt0167260  The Lord of the Rings: The Return of the King ...  2003
29    tt0167261       The Lord of the Rings: The Two Towers (2002)  2002
...         ...                                                ...   ...
9970  tt0469897                                     Diggers (2006)  2006
9971  tt0110064                               House Party 3 (1994)  1994
9972  tt1629391                              Tere Bin Laden (2010)  2010
9973  tt0878674                                      Garage (2007)  2007
9974  tt0076391                                      Mimino (1977)  1977
9975  tt1316037                  Birdemic: Shock and Terror (2008)  2008
9976  tt0197094         What Becomes of the Broken Hearted? (1999)  1999
9977  tt0092608                           Back to the Beach (1987)  1987
9978  tt0093175                                 Hello Again (1987)  1987
9979  tt1034320                            Major Movie Star (2008)  2008
9980  tt0066476                          The Touch of Satan (1971)  1971
9981  tt1281374                                   Don McKay (2009)  2009
9982  tt0263124                                  Brainstorm (2001)  2001
9983  tt0368259                 Sex Lives of the Potato Men (2004)  2004
9984  tt0067333                                      Lawman (1971)  1971
9985  tt0065669                          The Dunwich Horror (1970)  1970
9986  tt0048198                              I Live in Fear (1955)  1955
9987  tt0100046                          The Long Walk Home (1990)  1990
9988  tt0116247                                     Evil Ed (1995)  1995
9989  tt0101356                                 Another You (1991)  1991
9990  tt0421090                                  Zerophilia (2005)  2005
9991  tt0067227                The Merchant of Four Seasons (1971)  1971
9992  tt0339727                                   Stateside (2004)  2004
9993  tt0218581                                Scarlet Diva (2000)  2000
9994  tt0118635                                      Aprile (1998)  1998
9995  tt0807721                                     Meduzot (2007)  2007
9996  tt0339642                              Daltry Calhoun (2005)  2005
9997  tt0060880                      The Quiller Memorandum (1966)  1966
9998  tt0152836                                        Taal (1999)  1999
9999  tt0279977                              The Navigators (2001)  2001

      rating   votes   duration                                     genres
0        9.2  619479  142 mins.                                Crime|Drama
1        9.0  490065  154 mins.                             Crime|Thriller
2        8.8  458173  139 mins.                     Drama|Mystery|Thriller
3        8.7  448114  136 mins.                    Action|Adventure|Sci-Fi
4        8.9  385149  148 mins.           Action|Adventure|Sci-Fi|Thriller
5        8.7  368994  142 mins.                       Comedy|Drama|Romance
6        8.6  338332  122 mins.                                      Drama
7        8.1  336855  162 mins.            Action|Adventure|Fantasy|Sci-Fi
8        8.9  325888  195 mins.                Biography|Drama|History|War
9        8.8  320105  124 mins.             Action|Adventure|Family|Sci-Fi
10       8.3  316613  140 mins.                Action|Crime|Drama|Thriller
11       8.7  306624  106 mins.                     Crime|Mystery|Thriller
12       8.7  293081  118 mins.                             Crime|Thriller
13       7.4  284245  194 mins.            Adventure|Drama|History|Romance
14       8.4  281446  177 mins.         Action|Biography|Drama|History|War
15       8.2  278210  107 mins.                     Drama|Mystery|Thriller
16       8.2  272983  111 mins.                      Action|Crime|Thriller
17       8.8  270728  146 mins.             Biography|Crime|Drama|Thriller
18       7.8  269328  117 mins.                 Action|Fantasy|History|War
19       8.4  258396  130 mins.                     Drama|Mystery|Thriller
20       8.4  247390   99 mins.                     Crime|Mystery|Thriller
21       8.6  244568  110 mins.                       Crime|Drama|Thriller
22       8.4  243660  189 mins.                Crime|Drama|Fantasy|Mystery
23       8.4  240995  153 mins.                        Adventure|Drama|War
24       8.5  229364   98 mins.  Animation|Adventure|Family|Romance|Sci-Fi
25       8.9  555122  152 mins.                Action|Crime|Drama|Thriller
26       9.2  474189  175 mins.                                Crime|Drama
27       8.8  451263  178 mins.             Action|Adventure|Drama|Fantasy
28       8.8  428791  201 mins.             Action|Adventure|Drama|Fantasy
29       8.7  383113  179 mins.             Action|Adventure|Drama|Fantasy
...      ...     ...        ...                                        ...
9970     6.4    1358   96 mins.                               Comedy|Drama
9971     3.1    1357  100 mins.                       Comedy|Music|Romance
9972     7.2    1357   95 mins.                               Comedy|Drama
9973     6.9    1356   00 mins.                                      Drama
9974     8.2    1356   97 mins.                                     Comedy
9975     2.0    1366   90 mins.                    Horror|Romance|Thriller
9976     6.3    1365   00 mins.                                      Drama
9977     5.1    1364   92 mins.                                     Comedy
9978     4.5    1364   96 mins.               Comedy|Drama|Fantasy|Romance
9979     3.8    1364   98 mins.                 Adventure|Comedy|Drama|War
9980     2.0    1364   90 mins.                                     Horror
9981     6.0    1363   87 mins.                     Drama|Thriller|Mystery
9982     7.8    1362   74 mins.                                      Drama
9983     4.3    1362   82 mins.                                     Comedy
9984     6.8    1362   99 mins.                                    Western
9985     5.1    1361   90 mins.                                     Horror
9986     7.3    1360  103 mins.                                      Drama
9987     7.2    1360   97 mins.                              Drama|History
9988     5.0    1359   93 mins.                              Horror|Comedy
9989     4.9    1359   98 mins.                               Comedy|Crime
9990     6.3    1359   90 mins.                             Comedy|Romance
9991     7.6    1359   88 mins.                                      Drama
9992     5.8    1358   97 mins.                        Drama|Music|Romance
9993     5.2    1358   91 mins.                                      Drama
9994     6.7    1358   78 mins.                                     Comedy
9995     7.0    1357   78 mins.                                      Drama
9996     5.2    1357  100 mins.                 Comedy|Drama|Music|Romance
9997     6.5    1356  104 mins.                     Drama|Mystery|Thriller
9998     6.5    1356  179 mins.                            Musical|Romance
9999     6.9    1356   96 mins.                               Comedy|Drama

[10000 rows x 7 columns]>

# Cleaning

1. Drop all the missing rows which contain _any_ column with missing data
2. Convert the `duration` column to numerical representation of seconds
3. Remove the year from `title` column

1.df.dropna(), this drops all missing data in the rows and columns

In [7]:
df.dropna()

,ID,title,year,rating,votes,duration,genres
0,tt0111161,The Shawshank Redemption (1994),1994,9.2,619479,142 mins.,Crime|Drama
1,tt0110912,Pulp Fiction (1994),1994,9.0,490065,154 mins.,Crime|Thriller
2,tt0137523,Fight Club (1999),1999,8.8,458173,139 mins.,Drama|Mystery|Thriller
3,tt0133093,The Matrix (1999),1999,8.7,448114,136 mins.,Action|Adventure|Sci-Fi
4,tt1375666,Inception (2010),2010,8.9,385149,148 mins.,Action|Adventure|Sci-Fi|Thriller
5,tt0109830,Forrest Gump (1994),1994,8.7,368994,142 mins.,Comedy|Drama|Romance
6,tt0169547,American Beauty (1999),1999,8.6,338332,122 mins.,Drama
7,tt0499549,Avatar (2009),2009,8.1,336855,162 mins.,Action|Adventure|Fantasy|Sci-Fi
8,tt0108052,Schindler's List (1993),1993,8.9,325888,195 mins.,Biography|Drama|History|War
9,tt0080684,Star Wars: Episode V - The Empire Strikes Back...,1980,8.8,320105,124 mins.,Action|Adventure|Family|Sci-Fi
10,tt0372784,Batman Begins (2005),2005,8.3,316613,140 mins.,Action|Crime|Drama|Thriller
11,tt0114814,The Usual Suspects (1995),1995,8.7,306624,106 mins.,Crime|Mystery|Thriller
12,tt0102926,The Silence of the Lambs (1991),1991,8.7,293081,118 mins.,Crime|Thriller
13,tt0120338,Titanic (1997),1997,7.4,284245,194 mins.,Adventure|Drama|History|Romance
14,tt0112573,Braveheart (1995),1995,8.4,281446,177 mins.,Action|Biography|Drama|History|War
15,tt0167404,The Sixth Sense (1999),1999,8.2,278210,107 mins.,Drama|Mystery|Thriller
16,tt0266697,Kill Bill: Vol. 1 (2003),2003,8.2,272983,111 mins.,Action|Crime|Thriller
17,tt0099685,Goodfellas (1990),1990,8.8,270728,146 mins.,Biography|Crime|Drama|Thriller
18,tt0416449,300 (2006),2006,7.8,269328,117 mins.,Action|Fantasy|History|War
19,tt0482571,The Prestige (2006),2006,8.4,258396,130 mins.,Drama|Mystery|Thriller
20,tt0105236,Reservoir Dogs (1992),1992,8.4,247390,99 mins.,Crime|Mystery|Thriller
21,tt0110413,Leon: The Professional (1994),1994,8.6,244568,110 mins.,Crime|Drama|Thriller
22,tt0120689,The Green Mile (1999),1999,8.4,243660,189 mins.,Crime|Drama|Fantasy|Mystery
23,tt0361748,Inglourious Basterds (2009),2009,8.4,240995,153 mins.,Adventure|Drama|War
24,tt0910970,WALL\xb7E (2008),2008,8.5,229364,98 mins.,Animation|Adventure|Family|Romance|Sci-Fi
25,tt0468569,The Dark Knight (2008),2008,8.9,555122,152 mins.,Action|Crime|Drama|Thriller
26,tt0068646,The Godfather (1972),1972,9.2,474189,175 mins.,Crime|Drama
27,tt0120737,The Lord of the Rings: The Fellowship of the R...,2001,8.8,451263,178 mins.,Action|Adventure|Drama|Fantasy
28,tt0167260,The Lord of the Rings: The Return of the King ...,2003,8.8,428791,201 mins.,Action|Adventure|Drama|Fantasy
29,tt0167261,The Lord of the Rings: The Two Towers (2002),2002,8.7,383113,179 mins.,Action|Adventure|Drama|Fantasy
...,...,...,...,...,...,...,...
9970,tt0469897,Diggers (2006),2006,6.4,1358,96 mins.,Comedy|Drama
9971,tt0110064,House Party 3 (1994),1994,3.1,1357,100 mins.,Comedy|Music|Romance
9972,tt1629391,Tere Bin Laden (2010),2010,7.2,1357,95 mins.,Comedy|Drama
9973,tt0878674,Garage (2007),2007,6.9,1356,00 mins.,Drama
9974,tt0076391,Mimino (1977),1977,8.2,1356,97 mins.,Comedy
9975,tt1316037,Birdemic: Shock and Terror (2008),2008,2.0,1366,90 mins.,Horror|Romance|Thriller
9976,tt0197094,What Becomes of the Broken Hearted? (1999),1999,6.3,1365,00 mins.,Drama
9977,tt0092608,Back to the Beach (1987),1987,5.1,1364,92 mins.,Comedy
9978,tt0093175,Hello Again (1987),1987,4.5,1364,96 mins.,Comedy|Drama|Fantasy|Romance
9979,tt1034320,Major Movie Star (2008),2008,3.8,1364,98 mins.,Adventure|Comedy|Drama|War
9980,tt0066476,The Touch of Satan (1971),1971,2.0,1364,90 mins.,Horror
9981,tt1281374,Don McKay (2009),2009,6.0,1363,87 mins.,Drama|Thriller|Mystery
9982,tt0263124,Brainstorm (2001),2001,7.8,1362,74 mins.,Drama
9983,tt0368259,Sex Lives of the Potato Men (2004),2004,4.3,1362,82 mins.,Comedy
9984,tt0067333,Lawman (1971),1971,6.8,1362,99 mins.,Western
9985,tt0065669,The Dunwich Horror (1970),1970,5.1,1361,90 mins.,Horror
9986,tt0048198,I Live in Fear (1955),1955,7.3,1360,103 mins.,Drama
9987,tt0100046,The Long Walk Home (1990),1990,7.2,1360,97 mins.,Drama|History
9988,tt0116247,Evil Ed (1995),1995,5.0,1359,93 mins.,Horror|Comedy
9989,tt0101356,Another You (1991),1991,4.9,1359,98 mins.,Comedy|Crime
9990,tt0421090,Zerophilia (2005),2005,6.3,1359,90 mins.,Comedy|Romance
9991,tt0067227,The Merchant of Four Seasons (1971),1971,7.6,1359,88 mins.,Drama
9992,tt0339727,Stateside (2004),2004,5.8,1358,97 mins.,Drama|Music|Romance
9993,tt0218581,Scarlet Diva (2000),2000,5.2,1358,91 mins.,Drama
9994,tt0118635,Aprile (1998),1998,6.7,1358,78 mins.,Comedy
9995,tt0807721,Meduzot (2007),2007,7.0,1357,78 mins.,Drama
9996,tt0339642,Daltry Calhoun (2005),2005,5.2,1357,100 mins.,Comedy|Drama|Music|Romance
9997,tt0060880,The Quiller Memorandum (1966),1966,6.5,1356,104 mins.,Drama|Mystery|Thriller
9998,tt0152836,Taal (1999),1999,6.5,1356,179 mins.,Musical|Romance
9999,tt0279977,The Navigators (2001),2001,6.9,1356,96 mins.,Comedy|Drama

#Convert the `duration` column to numerical representation of seconds

In [27]:
df1 = df['duration'].str.split(' mins.', expand=True)
df['duration']=(df1[0].astype(int))*60
df.head()

,ID,title,year,rating,votes,duration,genres
0,tt0111161,The Shawshank Redemption (1994),1994,9.2,619479,8520,Crime|Drama
1,tt0110912,Pulp Fiction (1994),1994,9.0,490065,9240,Crime|Thriller
2,tt0137523,Fight Club (1999),1999,8.8,458173,8340,Drama|Mystery|Thriller
3,tt0133093,The Matrix (1999),1999,8.7,448114,8160,Action|Adventure|Sci-Fi
4,tt1375666,Inception (2010),2010,8.9,385149,8880,Action|Adventure|Sci-Fi|Thriller

## Concatenating

1. Read `crew_data.tsv.gz` to DataFrame named `movie_crew_df` with columns `ID, director_ids` indexed by `ID` (forget the rest of the columns)
2. Read `person_data.tsv.gz` to DataFrame named `person_df` with columns `person_ID, name` indexed by `person_ID` (forget the rest of the columns)
3. Merge `movie_crew_df` into `df` with `ID`s and drop the columns without necessary data (hint `outer`-join)
4. Remove movies with more than one director and rename `director_ids` => `director_id`
5. Merge `df` with `person_df` on `director_id`, remove `director_id` and `person_ID` columns, rename `name` => `director`

Read crew_data.tsv.gz to DataFrame named movie_crew_df with columns ID, director_ids indexed by ID (forget the rest of the columns).

In [28]:

movie_crew_df= pd.read_csv('crew_data.tsv', delimiter="\t")
movie_crew_df=movie_crew_df.rename(columns={'tconst':'ID','directors':'director_ids'})
movie_crew_df.set_index("ID")
movie_crew_df.head()

          ID director_ids writers
0  tt0000001    nm0005690      \N
1  tt0000002    nm0721526      \N
2  tt0000003    nm0721526      \N
3  tt0000004    nm0721526      \N
4  tt0000005    nm0005690      \N

In [29]:
movie_crew_df=movie_crew_df.drop(columns='writers')
movie_crew_df.head()

          ID director_ids
0  tt0000001    nm0005690
1  tt0000002    nm0721526
2  tt0000003    nm0721526
3  tt0000004    nm0721526
4  tt0000005    nm0005690

In [20]:
import pandas as pd
person_df = pd.read_csv("name_data.tsv", delimiter= "\t", header = 0, usecols=(0,1), names=["person ID","name"])
person_df.head()

   person ID             name
0  nm0000001     Fred Astaire
1  nm0000002    Lauren Bacall
2  nm0000003  Brigitte Bardot
3  nm0000004     John Belushi
4  nm0000005   Ingmar Bergman

In [30]:
df=pd.merge(movie_crew_df, df, on='ID')
df.head()

,ID,director_ids,title,year,rating,votes,duration,genres
0,tt0035423,nm0003506,Kate & Leopold (2001),2001,6.2,26738,7080,Comedy|Fantasy|Romance
1,tt0041719,nm0168413,Orpheus (1950),1950,8.0,3561,5700,Fantasy|Drama|Romance
2,tt0041931,nm0744023,Stromboli (1950),1950,7.1,1527,6420,Drama
3,tt0042179,nm0006943,Abbott and Costello in the Foreign Legion (1950),1950,6.3,1722,4800,Adventure|Comedy
4,tt0042192,nm0000581,All About Eve (1950),1950,8.5,39729,8280,Drama

In [9]:
indexNames = df[((df['director_ids'].str.len()) > 9)].index
df.drop(indexNames , inplace=True)

In [10]:
df.head(20)

,ID,director_ids,title,year,rating,votes,duration,genres
0,tt0035423,nm0003506,Kate & Leopold (2001),2001,6.2,26738,118 mins.,Comedy|Fantasy|Romance
1,tt0041719,nm0168413,Orpheus (1950),1950,8.0,3561,95 mins.,Fantasy|Drama|Romance
2,tt0041931,nm0744023,Stromboli (1950),1950,7.1,1527,107 mins.,Drama
3,tt0042179,nm0006943,Abbott and Costello in the Foreign Legion (1950),1950,6.3,1722,80 mins.,Adventure|Comedy
4,tt0042192,nm0000581,All About Eve (1950),1950,8.5,39729,138 mins.,Drama
6,tt0042208,nm0001379,The Asphalt Jungle (1950),1950,8.0,9451,112 mins.,Crime|Film-Noir|Drama
7,tt0042276,nm0002030,Born Yesterday (1950),1950,7.6,4117,103 mins.,Comedy|Drama|Romance
8,tt0042286,nm0202681,Broken Arrow (1950),1950,7.2,2436,93 mins.,Drama|Romance|Western
9,tt0042327,nm0485943,Cheaper by the Dozen (1950),1950,6.9,1984,86 mins.,Comedy|Drama|Family
11,tt0042367,nm0330456,Cyrano de Bergerac (1950),1950,7.4,1593,112 mins.,Drama|Romance
12,tt0042369,nm0005789,D.O.A. (1950),1950,7.4,4326,83 mins.,Drama|Film-Noir|Mystery
13,tt0042451,nm0591486,Father of the Bride (1950),1950,7.2,4325,92 mins.,Comedy|Romance
14,tt0042530,nm0507390,Gun Crazy (1950),1950,7.8,3702,86 mins.,Crime|Drama|Film-Noir|Romance|Thriller
15,tt0042531,nm0454771,The Gunfighter (1950),1950,7.8,3491,85 mins.,Western|Drama
16,tt0042546,nm0467396,Harvey (1950),1950,8.1,26683,104 mins.,Comedy|Drama|Fantasy
17,tt0042593,nm0712947,In a Lonely Place (1950),1950,8.0,7319,94 mins.,Drama|Film-Noir|Mystery|Romance|Thriller
18,tt0042619,nm0000975,Diary of a Country Priest (1951),1951,7.9,3256,115 mins.,Drama|Mystery
20,tt0042727,nm0003593,The Men (1950),1950,7.2,1648,85 mins.,Drama
21,tt0042788,nm0202088,Night and the City (1950),1950,8.0,3900,101 mins.,Crime|Film-Noir|Sport|Thriller
22,tt0042804,nm0000320,The Young and the Damned (1950),1950,8.2,6597,85 mins.,Crime|Drama

In [31]:
df=df.rename(columns={'director_ids':'director_id'})
df.head()

,ID,director_id,title,year,rating,votes,duration,genres
0,tt0035423,nm0003506,Kate & Leopold (2001),2001,6.2,26738,7080,Comedy|Fantasy|Romance
1,tt0041719,nm0168413,Orpheus (1950),1950,8.0,3561,5700,Fantasy|Drama|Romance
2,tt0041931,nm0744023,Stromboli (1950),1950,7.1,1527,6420,Drama
3,tt0042179,nm0006943,Abbott and Costello in the Foreign Legion (1950),1950,6.3,1722,4800,Adventure|Comedy
4,tt0042192,nm0000581,All About Eve (1950),1950,8.5,39729,8280,Drama

In [ ]:
df.shape

In [33]:
df2= pd.merge(df, person_df, left_on="director_id", right_on= "person ID", how= "inner")
df2

,ID,director_id,title,year,rating,votes,duration,genres,person ID,name
0,tt0035423,nm0003506,Kate & Leopold (2001),2001,6.2,26738,7080,Comedy|Fantasy|Romance,nm0003506,James Mangold
1,tt0113280,nm0003506,Heavy (1995),1995,7.0,2550,6300,Drama|Romance,nm0003506,James Mangold
2,tt0118887,nm0003506,Cop Land (1997),1997,6.9,38178,6240,Crime|Drama|Thriller,nm0003506,James Mangold
3,tt0172493,nm0003506,"Girl, Interrupted (1999)",1999,7.1,50814,7620,Biography|Drama,nm0003506,James Mangold
4,tt0309698,nm0003506,Identity (2003),2003,7.3,66794,5400,Drama|Mystery|Thriller,nm0003506,James Mangold
5,tt0358273,nm0003506,Walk the Line (2005),2005,7.9,95413,8160,Biography|Drama|Music|Romance,nm0003506,James Mangold
6,tt0381849,nm0003506,3:10 to Yuma (2007),2007,7.9,113802,7320,Action|Crime|Drama|Western,nm0003506,James Mangold
7,tt1013743,nm0003506,Knight and Day (2010),2010,6.4,46851,6540,Action|Adventure|Comedy|Thriller,nm0003506,James Mangold
8,tt0042179,nm0006943,Abbott and Costello in the Foreign Legion (1950),1950,6.3,1722,4800,Adventure|Comedy,nm0006943,Charles Lamont
9,tt0043255,nm0006943,Abbott and Costello Meet the Invisible Man (1951),1951,6.7,2261,4920,Comedy|Horror|Sci-Fi|Sport,nm0006943,Charles Lamont
10,tt0045468,nm0006943,Abbott and Costello Go to Mars (1953),1953,5.9,1808,4620,Comedy|Sci-Fi|Fantasy,nm0006943,Charles Lamont
11,tt0045469,nm0006943,Abbott and Costello Meet Dr. Jekyll and Mr. Hy...,1953,6.3,2095,4560,Comedy|Horror|Mystery|Sci-Fi,nm0006943,Charles Lamont
12,tt0047795,nm0006943,Abbott and Costello Meet the Mummy (1955),1955,6.2,2362,4740,Comedy|Adventure|Horror,nm0006943,Charles Lamont
13,tt0042192,nm0000581,All About Eve (1950),1950,8.5,39729,8280,Drama,nm0000581,Joseph L. Mankiewicz
14,tt0043915,nm0000581,People Will Talk (1951),1951,7.4,2183,6600,Drama|Romance,nm0000581,Joseph L. Mankiewicz
15,tt0044314,nm0000581,5 Fingers (1952),1952,7.7,1523,6480,Drama|Thriller,nm0000581,Joseph L. Mankiewicz
16,tt0045943,nm0000581,Julius Caesar (1953),1953,7.4,3922,7200,Drama|History,nm0000581,Joseph L. Mankiewicz
17,tt0046754,nm0000581,The Barefoot Contessa (1954),1954,7.0,4065,7680,Drama|Crime|Mystery|Romance,nm0000581,Joseph L. Mankiewicz
18,tt0048140,nm0000581,Guys and Dolls (1955),1955,7.2,5842,9000,Comedy|Musical|Romance,nm0000581,Joseph L. Mankiewicz
19,tt0053318,nm0000581,"Suddenly, Last Summer (1959)",1959,7.6,5383,6840,Drama|Mystery|Thriller,nm0000581,Joseph L. Mankiewicz
20,tt0056937,nm0000581,Cleopatra (1963),1963,6.8,9273,11520,Biography|Drama|History|Romance,nm0000581,Joseph L. Mankiewicz
21,tt0066448,nm0000581,There Was a Crooked Man... (1970),1970,7.1,1463,7560,Action|Comedy|Drama|Western,nm0000581,Joseph L. Mankiewicz
22,tt0069281,nm0000581,Sleuth (1972),1972,8.1,20601,8280,Mystery|Thriller,nm0000581,Joseph L. Mankiewicz
23,tt0042208,nm0001379,The Asphalt Jungle (1950),1950,8.0,9451,6720,Crime|Film-Noir|Drama,nm0001379,John Huston
24,tt0043265,nm0001379,The African Queen (1951),1951,8.0,36448,6300,Adventure|Drama|Romance|War,nm0001379,John Huston
25,tt0043961,nm0001379,The Red Badge of Courage (1951),1951,7.3,1868,4140,Drama|War,nm0001379,John Huston
26,tt0044926,nm0001379,Moulin Rouge (1952),1952,7.2,2310,7140,Biography|Drama|Music|Romance,nm0001379,John Huston
27,tt0046414,nm0001379,Beat the Devil (1953),1953,6.6,3622,5340,Adventure|Comedy|Crime|Drama|Romance,nm0001379,John Huston
28,tt0049513,nm0001379,Moby Dick (1956),1956,7.4,6573,6960,Adventure|Drama,nm0001379,John Huston
29,tt0050490,nm0001379,"Heaven Knows, Mr. Allison (1957)",1957,7.4,2976,6480,Action|Adventure|Drama|War,nm0001379,John Huston
...,...,...,...,...,...,...,...,...,...,...
3113,tt0487928,nm0001988,Dante 01 (2008),2008,5.0,2618,4920,Sci-Fi|Thriller,nm0001988,Marc Caro
3114,tt0490086,nm0001705,Big Stan (2007),2007,6.2,10831,6300,Action|Comedy,nm0001705,Rob Schneider
3115,tt0491747,nm0001631,Away from Her (2006),2006,7.6,11255,6600,Drama|Romance,nm0001631,Sarah Polley
3116,tt0496634,nm0000365,The Countess (2009),2009,6.2,1963,5880,Biography|Drama|History|Horror|Thriller,nm0000365,Julie Delpy
3117,tt0841044,nm0000365,2 Days in Paris (2007),2007,6.9,13199,5760,Comedy|Drama|Romance,nm0000365,Julie Delpy
3118,tt0499570,nm0000164,Slipstream (2007),2007,5.1,2980,5760,Comedy|Drama|Fantasy|Mystery|Sci-Fi|Thriller,nm0000164,Anthony Hopkins
3119,tt0760187,nm0000274,The Tripper (2006),2006,5.2,3867,5580,Horror,nm0000274,David Arquette
3120,tt0772193,nm0003150,Primeval (2007),2007,4.4,7197,5580,Action|Adventure|Horror|Thriller,nm0003150,Michael Katleman
3121,tt0783515,nm0004890,The Education of Charlie Banks (2007),2007,6.7,2349,6000,Drama,nm0004890,Fred Durst
3122,tt1091751,nm0004890,The Longshots (2008),2008,4.2,1998,5640,Comedy|Drama|Family|Sport,nm0004890,Fred Durst
3123,tt0795361,nm0006799,Cougar Club (2007),2007,4.1,2006,5580,Comedy,nm0006799,Christopher Duddy
3124,tt0806165,nm0010012,The Ramen Girl (2008),2008,6.0,2136,6120,Comedy|Drama|Romance,nm0010012,Robert Allan Ackerman
3125,tt0822849,nm0002055,Rails & Ties (2007),2007,6.8,2276,6060,Drama,nm0002055,Alison Eastwood
3126,tt0910970,nm0004056,WALL\xb7E (2008),2008,8.5,229364,5880,Animation|Adventure|Family|Romance|Sci-Fi,nm0004056,Andrew Stanton
3127,tt0954990,nm0006841,The Yellow Handkerchief (2008),2008,6.8,1985,6120,Drama|Romance,nm0006841,Udayan Prasad
3128,tt1042499,nm0000187,Filth and Wisdom (2008),2008,5.1,1367,0,Comedy|Drama|Music|Romance,nm0000187,Madonna
3129,tt1054588,nm0008953,Flash of Genius (2008),2008,6.9,6725,7140,Biography|Drama,nm0008953,Marc Abraham
3130,tt1063056,nm0003659,From Within (2008),2008,5.7,2607,5340,Horror|Mystery|Thriller,nm0003659,Phedon Papamichael
3131,tt1085507,nm0003482,The Square (2008),2008,6.8,2157,6300,Drama|Thriller,nm0003482,Nash Edgerton
3132,tt1117385,nm0006846,Felon (2008),2008,7.7,28754,6240,Crime|Drama,nm0006846,Ric Roman Waugh
3133,tt1147687,nm0001064,The Devil's Tomb (2009),2009,4.0,3157,5400,Action|Thriller|Horror|Sci-Fi,nm0001064,Jason Connery
3134,tt1167638,nm0006939,22 Bullets (2010),2010,6.6,8363,7020,Action|Crime|Thriller,nm0006939,Richard Berry
3135,tt1172233,nm0000106,Whip It (2009),2009,7.0,20156,6660,Drama|Sport,nm0000106,Drew Barrymore
3136,tt1196134,nm0000741,Crazy on the Outside (2010),2010,5.6,2198,5760,Comedy|Crime,nm0000741,Tim Allen
3137,tt1270291,nm0004611,Hunter Prey (2010),2010,5.9,1482,5400,Sci-Fi|Thriller,nm0004611,Sandy Collora
3138,tt1278379,nm0000450,Jack Goes Boating (2010),2010,6.4,2794,5460,Comedy|Drama|Romance,nm0000450,Philip Seymour Hoffman
3139,tt1356864,nm0000729,I'm Still Here (2010),2010,6.1,5053,6480,Comedy|Drama|Music,nm0000729,Casey Affleck
3140,tt1423894,nm0003557,Barney's Version (2010),2010,7.4,4513,8040,Drama,nm0003557,Richard J. Lewis
3141,tt1639426,nm0003939,Udaan (2010),2010,8.3,3832,8040,Drama,nm0003939,Vikramaditya Motwane
3142,tt1740707,nm0004217,TrollHunter (2010),2010,7.2,8927,5400,Comedy|Fantasy|Horror,nm0004217,André Øvredal

## Exploration

1. Find ten most longest movies
2. Find Best rated movies ordered by rating DESC and Title ASC
3. What is the average duration (in minutes) of a movie?
4. Get ten most productive directors
5. How many movie has been made in the 2000's?
6. Get all the movies directed by Akira Kurosawa ordered by year DESC

In [35]:
df2.sort_values(['duration'], ascending=[False],inplace=True)
df2

,ID,title,year,rating,votes,duration,genres,person ID,name
2308,tt0116477,Hamlet (1996),1996,7.7,19698,14520,Crime|Drama|Romance|Thriller,nm0000110,Kenneth Branagh
567,tt0087843,Once Upon a Time in America (1984),1984,8.4,85533,13740,Crime|Drama,nm0001466,Sergio Leone
222,tt0049833,The Ten Commandments (1956),1956,7.9,22789,13200,Adventure|Drama|History,nm0001124,Cecil B. DeMille
288,tt0056172,Lawrence of Arabia (1962),1962,8.5,89628,12960,Adventure|Biography|Drama|History|War,nm0000180,David Lean
97,tt0047478,Seven Samurai (1954),1954,8.8,111707,12420,Adventure|Drama,nm0000041,Akira Kurosawa
2120,tt0104797,Malcolm X (1992),1992,7.7,25577,12120,Biography|Drama|History,nm0000490,Spike Lee
2173,tt0167260,The Lord of the Rings: The Return of the King ...,2003,8.8,428791,12060,Action|Adventure|Drama|Fantasy,nm0001392,Peter Jackson
527,tt0071562,The Godfather: Part II (1974),1974,9.0,291169,12000,Crime|Drama,nm0000338,Francis Ford Coppola
801,tt0064451,A Touch of Zen (1971),1971,7.6,1374,12000,Action|Adventure,nm0002254,King Hu
289,tt0059113,Doctor Zhivago (1965),1965,8.0,30009,11820,Drama|Romance|War,nm0000180,David Lean
1159,tt0108052,Schindler's List (1993),1993,8.9,325888,11700,Biography|Drama|History|War,nm0000229,Steven Spielberg
1968,tt0120338,Titanic (1997),1997,7.4,284245,11640,Adventure|Drama|History|Romance,nm0000116,James Cameron
1652,tt0082979,Reds (1981),1981,7.4,9138,11640,Biography|Drama|History|Romance,nm0000886,Warren Beatty
1617,tt0113987,Nixon (1995),1995,7.1,14626,11520,Biography|Drama,nm0000231,Oliver Stone
20,tt0056937,Cleopatra (1963),1963,6.8,9273,11520,Biography|Drama|History|Romance,nm0000581,Joseph L. Mankiewicz
1196,tt0420332,Veer-Zaara (2004),2004,7.3,5099,11520,Drama|Musical|Romance,nm0007181,Yash Chopra
1277,tt0083987,Gandhi (1982),1982,8.1,60375,11460,Biography|Drama|History,nm0000277,Richard Attenborough
1578,tt0111756,Wyatt Earp (1994),1994,6.4,17225,11460,Action|Adventure|Biography|Romance|Western,nm0001410,Lawrence Kasdan
2730,tt0120689,The Green Mile (1999),1999,8.4,243660,11340,Crime|Drama|Fantasy|Mystery,nm0001104,Frank Darabont
1649,tt0101373,At Play in the Fields of the Lord (1991),1991,6.5,1813,11340,Drama|Romance,nm0002199,Hector Babenco
1614,tt0102138,JFK (1991),1991,8.0,64837,11340,Biography|Drama|History|Mystery|Thriller,nm0000231,Oliver Stone
255,tt0083922,Fanny and Alexander (1982),1982,8.2,17085,11280,Drama|Fantasy|Mystery,nm0000005,Ingmar Bergman
2851,tt0175880,Magnolia (1999),1999,8.0,135347,11280,Drama,nm0000759,Paul Thomas Anderson
2175,tt0360717,King Kong (2005),2005,7.5,149542,11220,Action|Adventure|Drama|Romance|Thriller,nm0001392,Peter Jackson
913,tt0108122,Short Cuts (1993),1993,7.7,19990,11220,Comedy|Drama,nm0000265,Robert Altman
501,tt0080009,Tess (1979),1979,7.2,5583,11160,Drama|Romance,nm0000591,Roman Polanski
367,tt0055031,Judgment at Nuremberg (1961),1961,8.3,17027,11160,Drama|History,nm0006452,Stanley Kramer
106,tt0058888,Red Beard (1965),1965,8.1,5747,11100,Drama,nm0000041,Akira Kurosawa
2762,tt0432637,Krrish (2006),2006,6.0,3235,11100,Action|Adventure|Romance|Sci-Fi,nm0004363,Rakesh Roshan
303,tt0072684,Barry Lyndon (1975),1975,8.1,45618,11040,Drama|Romance|War,nm0000040,Stanley Kubrick
...,...,...,...,...,...,...,...,...,...
1184,tt0093966,The Sicilian (1987),1987,5.2,2104,0,Action|Crime|Drama,nm0001047,Michael Cimino
877,tt0080149,Woyzeck (1979),1979,7.2,3624,0,Drama,nm0001348,Werner Herzog
2134,tt0337721,The Snow Walker (2003),2003,7.5,4285,0,Adventure|Drama,nm0001747,Charles Martin Smith
1661,tt0097223,Time of the Gypsies (1988),1988,8.1,8172,0,Comedy|Crime|Drama|Fantasy,nm0001437,Emir Kusturica
924,tt0074084,1900 (1976),1976,7.7,9444,0,Drama|History,nm0000934,Bernardo Bertolucci
3070,tt1242432,I Spit on Your Grave: Unrated (2010),2010,6.3,11167,0,Crime|Horror|Thriller,nm0003458,Steven R. Monroe
290,tt0066319,Ryan's Daughter (1970),1970,7.4,3576,0,Drama|Romance,nm0000180,David Lean
364,tt0051525,The Defiant Ones (1958),1958,7.7,5032,0,Crime|Drama|Thriller,nm0006452,Stanley Kramer
3092,tt0446463,The Secret (2007),2007,6.2,1925,0,Drama|Horror|Romance,nm0001641,Vincent Perez
2624,tt0106309,Joshua Tree (1993),1993,5.1,2100,0,Action|Adventure|Crime|Drama|Mystery|Thriller,nm0002184,Vic Armstrong
2893,tt0119861,Pardes (1997),1997,6.8,1582,0,Musical|Romance|Action|Drama,nm0007131,Subhash Ghai
3017,tt0253997,The King of the Street Cleaners (1977),1977,8.1,1951,0,Comedy,nm0006703,Zeki Ökten
304,tt0081505,The Shining (1980),1980,8.5,212988,0,Drama|Horror|Mystery,nm0000040,Stanley Kubrick
1799,tt0095250,The Big Blue (1988),1988,7.4,19879,0,Adventure|Drama|Romance,nm0000108,Luc Besson
3025,tt0411270,The Beat That My Heart Skipped (2005),2005,7.3,8275,0,Action|Crime|Drama|Music|Romance|Thriller,nm0002191,Jacques Audiard
589,tt0094074,Superman IV: The Quest for Peace (1987),1987,3.4,17005,0,Action|Adventure|Family|Fantasy|Sci-Fi,nm0002089,Sidney J. Furie
2611,tt1077258,Planet Terror (2007),2007,7.5,74950,0,Action|Horror|Sci-Fi,nm0001675,Robert Rodriguez
2040,tt0091083,From Beyond (1986),1986,6.7,5092,0,Horror|Sci-Fi,nm0002340,Stuart Gordon
1148,tt0075860,Close Encounters of the Third Kind (1977),1977,7.8,65768,0,Drama|Sci-Fi,nm0000229,Steven Spielberg
849,tt0065761,The Cat o' Nine Tails (1971),1971,6.6,3050,0,Mystery|Thriller,nm0000783,Dario Argento
2754,tt0780608,Smiley Face (2007),2007,5.7,7572,0,Adventure|Comedy,nm0000777,Gregg Araki
1182,tt0080855,Heaven's Gate (1980),1980,6.5,5019,0,Drama|History|Western,nm0001047,Michael Cimino
2266,tt1486193,5 Days of War (2011),2011,5.7,3436,0,Action|Drama|War,nm0001317,Renny Harlin
368,tt0057193,It's a Mad Mad Mad Mad World (1963),1963,7.4,15890,0,Action|Adventure|Comedy|Crime,nm0006452,Stanley Kramer
1437,tt0106660,Dangerous Game (1993),1993,5.2,1822,0,Drama,nm0001206,Abel Ferrara
862,tt0804507,Mother of Tears (2007),2007,5.2,4188,0,Fantasy|Horror,nm0000783,Dario Argento
406,tt0054389,Shoot the Piano Player (1960),1960,7.6,6082,0,Crime|Drama|Music|Romance|Thriller,nm0000076,François Truffaut
81,tt0071487,The Phantom of Liberty (1974),1974,7.9,4544,0,Comedy|Drama,nm0000320,Luis Buñuel
2089,tt0792965,"Ensemble, c'est tout (2007)",2007,6.7,4602,0,Drama|Romance,nm0001945,Claude Berri
2941,tt0131704,The Adventures of Rocky & Bullwinkle (2000),2000,4.1,10968,0,Animation|Adventure|Comedy|Family|Fantasy,nm0005197,Des McAnuff

In [34]:
df2=df2.drop(columns=["director_id"])

In [36]:
df2.head()

,ID,title,year,rating,votes,duration,genres,person ID,name
2308,tt0116477,Hamlet (1996),1996,7.7,19698,14520,Crime|Drama|Romance|Thriller,nm0000110,Kenneth Branagh
567,tt0087843,Once Upon a Time in America (1984),1984,8.4,85533,13740,Crime|Drama,nm0001466,Sergio Leone
222,tt0049833,The Ten Commandments (1956),1956,7.9,22789,13200,Adventure|Drama|History,nm0001124,Cecil B. DeMille
288,tt0056172,Lawrence of Arabia (1962),1962,8.5,89628,12960,Adventure|Biography|Drama|History|War,nm0000180,David Lean
97,tt0047478,Seven Samurai (1954),1954,8.8,111707,12420,Adventure|Drama,nm0000041,Akira Kurosawa

In [38]:
df2.sort_values(['votes', 'title'], ascending=[False, True])
df2.head()

,ID,title,year,rating,votes,duration,genres,person ID,name
2308,tt0116477,Hamlet (1996),1996,7.7,19698,14520,Crime|Drama|Romance|Thriller,nm0000110,Kenneth Branagh
567,tt0087843,Once Upon a Time in America (1984),1984,8.4,85533,13740,Crime|Drama,nm0001466,Sergio Leone
222,tt0049833,The Ten Commandments (1956),1956,7.9,22789,13200,Adventure|Drama|History,nm0001124,Cecil B. DeMille
288,tt0056172,Lawrence of Arabia (1962),1962,8.5,89628,12960,Adventure|Biography|Drama|History|War,nm0000180,David Lean
97,tt0047478,Seven Samurai (1954),1954,8.8,111707,12420,Adventure|Drama,nm0000041,Akira Kurosawa

In [39]:
num = df2['duration'].mean()/60
num

110.67324212535794

In [44]:
df2=df2.rename(columns={'name':'director'})
df2.head()

,ID,title,year,rating,votes,duration,genres,person ID,director
2308,tt0116477,Hamlet (1996),1996,7.7,19698,14520,Crime|Drama|Romance|Thriller,nm0000110,Kenneth Branagh
567,tt0087843,Once Upon a Time in America (1984),1984,8.4,85533,13740,Crime|Drama,nm0001466,Sergio Leone
222,tt0049833,The Ten Commandments (1956),1956,7.9,22789,13200,Adventure|Drama|History,nm0001124,Cecil B. DeMille
288,tt0056172,Lawrence of Arabia (1962),1962,8.5,89628,12960,Adventure|Biography|Drama|History|War,nm0000180,David Lean
97,tt0047478,Seven Samurai (1954),1954,8.8,111707,12420,Adventure|Drama,nm0000041,Akira Kurosawa

In [46]:
df2['director'].value_counts()[:10]

Woody Allen         40
Clint Eastwood      31
Sidney Lumet        27
Steven Spielberg    24
Robert Altman       24
Brian De Palma      23
John Huston         23
Joel Schumacher     22
Martin Scorsese     21
Blake Edwards       21
Name: director, dtype: int64

In [47]:
s = df2.apply(lambda x: True if x['year'] == 2000 else False , axis=1)

numOfRows = len(s[s == True].index)

print(numOfRows)

85

In [48]:
gap= df2[df2.director== 'Akira Kurosawa']
gap.head()

,ID,title,year,rating,votes,duration,genres,person ID,director
97,tt0047478,Seven Samurai (1954),1954,8.8,111707,12420,Adventure|Drama,nm0000041,Akira Kurosawa
106,tt0058888,Red Beard (1965),1965,8.1,5747,11100,Drama,nm0000041,Akira Kurosawa
109,tt0080979,Kagemusha (1980),1980,7.9,12492,10800,Drama|History|War,nm0000041,Akira Kurosawa
95,tt0043614,The Idiot (1951),1951,7.5,1680,9960,Drama,nm0000041,Akira Kurosawa
110,tt0089881,Ran (1985),1985,8.3,39096,9720,Action|Drama|War,nm0000041,Akira Kurosawa

### Get all the movies directed by Akira Kurosawa ordered by year DESC

In [49]:
gap.sort_values(['year'],ascending=False)

,ID,title,year,rating,votes,duration,genres,person ID,director
112,tt0107474,Madadayo (1993),1993,7.4,1935,8040,Drama,nm0000041,Akira Kurosawa
111,tt0101991,Rhapsody in August (1991),1991,7.2,2830,5880,Drama,nm0000041,Akira Kurosawa
110,tt0089881,Ran (1985),1985,8.3,39096,9720,Action|Drama|War,nm0000041,Akira Kurosawa
109,tt0080979,Kagemusha (1980),1980,7.9,12492,10800,Drama|History|War,nm0000041,Akira Kurosawa
108,tt0071411,Dersu Uzala (1975),1975,8.2,9180,8640,Adventure|Drama,nm0000041,Akira Kurosawa
107,tt0065649,Dodes'ka-den (1970),1970,7.6,2371,8400,Drama,nm0000041,Akira Kurosawa
106,tt0058888,Red Beard (1965),1965,8.1,5747,11100,Drama,nm0000041,Akira Kurosawa
105,tt0057565,High and Low (1963),1963,8.3,8603,8520,Crime|Drama|Thriller,nm0000041,Akira Kurosawa
104,tt0056443,Sanjuro (1962),1962,8.1,9739,5760,Action|Drama|Thriller,nm0000041,Akira Kurosawa
103,tt0055630,Yojimbo (1961),1961,8.4,33878,6600,Action|Crime|Drama|Thriller,nm0000041,Akira Kurosawa
102,tt0054460,The Bad Sleep Well (1960),1960,8.0,3356,9060,Crime|Drama|Thriller,nm0000041,Akira Kurosawa
101,tt0051808,The Hidden Fortress (1958),1958,8.1,12535,8340,Action|Adventure,nm0000041,Akira Kurosawa
99,tt0050330,The Lower Depths (1957),1957,7.5,1901,8220,Drama,nm0000041,Akira Kurosawa
100,tt0050613,Throne of Blood (1957),1957,8.1,13559,6600,Drama,nm0000041,Akira Kurosawa
98,tt0048198,I Live in Fear (1955),1955,7.3,1360,6180,Drama,nm0000041,Akira Kurosawa
97,tt0047478,Seven Samurai (1954),1954,8.8,111707,12420,Adventure|Drama,nm0000041,Akira Kurosawa
96,tt0044741,Ikiru (1952),1952,8.3,18948,8580,Drama,nm0000041,Akira Kurosawa
95,tt0043614,The Idiot (1951),1951,7.5,1680,9960,Drama,nm0000041,Akira Kurosawa
94,tt0042876,Rashomon (1950),1950,8.4,46250,5280,Crime|Drama|Mystery,nm0000041,Akira Kurosawa